language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t frontier-sco/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true frontier-sco/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-054306867602"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
