language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t frontier-sco/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true frontier-sco/docker-react npm run test

