FROM node:alpine as builder
WORKDIR '/home/node'
COPY package.json .
RUN npm install
COPY --chown=node:node . .
RUN npm run build
 
FROM nginx
COPY --from=builder --chown=node:node /home/node/build /usr/share/nginx/html
